#!/usr/bin/env bash
# Usage: script/test
#
# Run Go and Cucumber test suites for hub.

set -e

case "$1" in
"" )
  ;;
-h | --help )
  sed -ne '/^#/!q;s/.\{1,2\}//;1d;p' < "$0"
  exit
  ;;
* )
  "$0" --help >&2
  exit 1
esac

STATUS=0

trap "exit 1" INT

script/build
script/build test || STATUS="$?"
# script/ruby-test || STATUS="$?"

if [ -n "$CI" ] && [ -n "$GITHUB_OAUTH" ]; then
  curl https://api.github.com/repos/github/hub/releases/tags/v2.2.2-rc0 -H "authorization: token $GITHUB_OAUTH"
fi

exit "$STATUS"
